name: CI

on: [push]

jobs:
    sast_scan:
        name: Run Bandit scan
        runs-on: ubuntu-latest
        
        steps:
        - name: checkout code
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'

        - name: Install Bandit
          run: pip install bandit

        - name: Run Bandit
          run: bandit -ll -ii -r . -f json -o bandit-report.json

        - name: Upload Bandit report
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: bandit-report
            path: bandit-report.json
            
    docker_job:
        name: Build and scan Docker image
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker
          uses: docker/setup-docker-action@v4
          with:
            docker_version: '20.10.7'

        - name: Build Docker image
          run: docker build -f Dockerfile -t myapp:${{ github.run_id }} .

        - name: Scan image with Scout
          uses: docker/scout-action@v1
          with:
            dockerhub-user: ${{ secrets.DOCKER_USERNAME }}
            dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
            command: quickview,cves

